/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * BandService | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfInvitation,
  ApiResponseOfListOfGetMyInvitationsResponse,
  ApiResponseOfint,
  RespondInvitationRequest
} from './models';

import { customInstance } from '../../axios-instance';





export const getMyInvitations = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfListOfGetMyInvitationsResponse>(
      {url: `/band-api/user/invitations`, method: 'GET', signal
    },
      );
    }
  



export const getGetMyInvitationsQueryKey = () => {
    return [
    `/band-api/user/invitations`
    ] as const;
    }

    
export const getGetMyInvitationsQueryOptions = <TData = Awaited<ReturnType<typeof getMyInvitations>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvitations>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyInvitationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyInvitations>>> = ({ signal }) => getMyInvitations(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyInvitations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyInvitationsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyInvitations>>>
export type GetMyInvitationsQueryError = unknown


export function useGetMyInvitations<TData = Awaited<ReturnType<typeof getMyInvitations>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvitations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInvitations>>,
          TError,
          Awaited<ReturnType<typeof getMyInvitations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInvitations<TData = Awaited<ReturnType<typeof getMyInvitations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvitations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInvitations>>,
          TError,
          Awaited<ReturnType<typeof getMyInvitations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInvitations<TData = Awaited<ReturnType<typeof getMyInvitations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvitations>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMyInvitations<TData = Awaited<ReturnType<typeof getMyInvitations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvitations>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyInvitationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const respondInvitation = (
    invitationId: string,
    respondInvitationRequest: RespondInvitationRequest,
 ) => {
      
      
      return customInstance<ApiResponseOfInvitation>(
      {url: `/band-api/user/invitations/${invitationId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: respondInvitationRequest
    },
      );
    }
  


export const getRespondInvitationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof respondInvitation>>, TError,{invitationId: string;data: RespondInvitationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof respondInvitation>>, TError,{invitationId: string;data: RespondInvitationRequest}, TContext> => {

const mutationKey = ['respondInvitation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof respondInvitation>>, {invitationId: string;data: RespondInvitationRequest}> = (props) => {
          const {invitationId,data} = props ?? {};

          return  respondInvitation(invitationId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RespondInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof respondInvitation>>>
    export type RespondInvitationMutationBody = RespondInvitationRequest
    export type RespondInvitationMutationError = unknown

    export const useRespondInvitation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof respondInvitation>>, TError,{invitationId: string;data: RespondInvitationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof respondInvitation>>,
        TError,
        {invitationId: string;data: RespondInvitationRequest},
        TContext
      > => {

      const mutationOptions = getRespondInvitationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getMyInvitationsCount = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfint>(
      {url: `/band-api/user/invitations/count`, method: 'GET', signal
    },
      );
    }
  



export const getGetMyInvitationsCountQueryKey = () => {
    return [
    `/band-api/user/invitations/count`
    ] as const;
    }

    
export const getGetMyInvitationsCountQueryOptions = <TData = Awaited<ReturnType<typeof getMyInvitationsCount>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvitationsCount>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyInvitationsCountQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyInvitationsCount>>> = ({ signal }) => getMyInvitationsCount(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyInvitationsCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyInvitationsCountQueryResult = NonNullable<Awaited<ReturnType<typeof getMyInvitationsCount>>>
export type GetMyInvitationsCountQueryError = unknown


export function useGetMyInvitationsCount<TData = Awaited<ReturnType<typeof getMyInvitationsCount>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvitationsCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInvitationsCount>>,
          TError,
          Awaited<ReturnType<typeof getMyInvitationsCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInvitationsCount<TData = Awaited<ReturnType<typeof getMyInvitationsCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvitationsCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInvitationsCount>>,
          TError,
          Awaited<ReturnType<typeof getMyInvitationsCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInvitationsCount<TData = Awaited<ReturnType<typeof getMyInvitationsCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvitationsCount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMyInvitationsCount<TData = Awaited<ReturnType<typeof getMyInvitationsCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvitationsCount>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyInvitationsCountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




