/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WBand.WebProxy | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetAuthLoginParams,
  SessionResponse
} from './models';

export type getAuthLoginResponse200 = {
  data: void
  status: 200
}

export type getAuthLoginResponseSuccess = (getAuthLoginResponse200) & {
  headers: Headers;
};
;

export type getAuthLoginResponse = (getAuthLoginResponseSuccess)

export const getGetAuthLoginUrl = (params?: GetAuthLoginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/login?${stringifiedParams}` : `/auth/login`
}

export const getAuthLogin = async (params?: GetAuthLoginParams, options?: RequestInit): Promise<getAuthLoginResponse> => {

  const res = await fetch(getGetAuthLoginUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAuthLoginResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getAuthLoginResponse
}



export type getAuthMeResponse200 = {
  data: SessionResponse
  status: 200
}

export type getAuthMeResponse401 = {
  data: void
  status: 401
}

export type getAuthMeResponseSuccess = (getAuthMeResponse200) & {
  headers: Headers;
};
export type getAuthMeResponseError = (getAuthMeResponse401) & {
  headers: Headers;
};

export type getAuthMeResponse = (getAuthMeResponseSuccess | getAuthMeResponseError)

export const getGetAuthMeUrl = () => {




  return `/auth/me`
}

export const getAuthMe = async ( options?: RequestInit): Promise<getAuthMeResponse> => {

  const res = await fetch(getGetAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAuthMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAuthMeResponse
}



export type postAuthLogoutResponse200 = {
  data: void
  status: 200
}

export type postAuthLogoutResponseSuccess = (postAuthLogoutResponse200) & {
  headers: Headers;
};
;

export type postAuthLogoutResponse = (postAuthLogoutResponseSuccess)

export const getPostAuthLogoutUrl = () => {




  return `/auth/logout`
}

export const postAuthLogout = async ( options?: RequestInit): Promise<postAuthLogoutResponse> => {

  const res = await fetch(getPostAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthLogoutResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postAuthLogoutResponse
}
