<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>bd8afe03-ac5e-49c5-ba12-131abe015773</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference
            Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets"
            Version="1.23.0"
        />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../../Common/Auth/Auth.csproj" />
        <ProjectReference Include="../../Common/Shared/Shared.csproj" />
        <ProjectReference Include="../../Common/WBand.ServiceDefaults/WBand.ServiceDefaults.csproj" />
    </ItemGroup>
</Project>
