name: Сборка и тестирование на любую ветку

on:
  push:
    # Отсутствие секции branches означает запуск на все пуши

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore WBand.slnx

      - name: Build Solution
        run: dotnet build WBand.slnx --no-restore

      - name: Test Solution
        run: dotnet test WBand.slnx --no-build --verbosity normal

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Web Dependencies
        working-directory: ./App/web
        run: bun install --frozen-lockfile

      - name: Build Web
        working-directory: ./App/web
        run: bun run build

      - name: Lint Web
        working-directory: ./App/web
        run: bun run lint
