/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * PlaybackService | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfListOfMixerPreset,
  ApiResponseOfMixerPreset,
  ApiResponseOfObject,
  CreateMixerPresetRequest,
  UpdateMixerPresetRequest
} from './models';

import { customInstance } from '../../axios-instance';





export const createMixerPreset = (
    songId: string,
    createMixerPresetRequest: CreateMixerPresetRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfMixerPreset>(
      {url: `/playback-api/songs/${songId}/mixer-presets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMixerPresetRequest, signal
    },
      );
    }
  


export const getCreateMixerPresetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMixerPreset>>, TError,{songId: string;data: CreateMixerPresetRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createMixerPreset>>, TError,{songId: string;data: CreateMixerPresetRequest}, TContext> => {

const mutationKey = ['createMixerPreset'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMixerPreset>>, {songId: string;data: CreateMixerPresetRequest}> = (props) => {
          const {songId,data} = props ?? {};

          return  createMixerPreset(songId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMixerPresetMutationResult = NonNullable<Awaited<ReturnType<typeof createMixerPreset>>>
    export type CreateMixerPresetMutationBody = CreateMixerPresetRequest
    export type CreateMixerPresetMutationError = unknown

    export const useCreateMixerPreset = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMixerPreset>>, TError,{songId: string;data: CreateMixerPresetRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMixerPreset>>,
        TError,
        {songId: string;data: CreateMixerPresetRequest},
        TContext
      > => {

      const mutationOptions = getCreateMixerPresetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getMixerPresets = (
    songId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfListOfMixerPreset>(
      {url: `/playback-api/songs/${songId}/mixer-presets`, method: 'GET', signal
    },
      );
    }
  



export const getGetMixerPresetsQueryKey = (songId?: string,) => {
    return [
    `/playback-api/songs/${songId}/mixer-presets`
    ] as const;
    }

    
export const getGetMixerPresetsQueryOptions = <TData = Awaited<ReturnType<typeof getMixerPresets>>, TError = unknown>(songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMixerPresets>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMixerPresetsQueryKey(songId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMixerPresets>>> = ({ signal }) => getMixerPresets(songId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(songId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMixerPresets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMixerPresetsQueryResult = NonNullable<Awaited<ReturnType<typeof getMixerPresets>>>
export type GetMixerPresetsQueryError = unknown


export function useGetMixerPresets<TData = Awaited<ReturnType<typeof getMixerPresets>>, TError = unknown>(
 songId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMixerPresets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMixerPresets>>,
          TError,
          Awaited<ReturnType<typeof getMixerPresets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMixerPresets<TData = Awaited<ReturnType<typeof getMixerPresets>>, TError = unknown>(
 songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMixerPresets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMixerPresets>>,
          TError,
          Awaited<ReturnType<typeof getMixerPresets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMixerPresets<TData = Awaited<ReturnType<typeof getMixerPresets>>, TError = unknown>(
 songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMixerPresets>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMixerPresets<TData = Awaited<ReturnType<typeof getMixerPresets>>, TError = unknown>(
 songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMixerPresets>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMixerPresetsQueryOptions(songId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getMixerPreset = (
    songId: string,
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfMixerPreset>(
      {url: `/playback-api/songs/${songId}/mixer-presets/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetMixerPresetQueryKey = (songId?: string,
    id?: string,) => {
    return [
    `/playback-api/songs/${songId}/mixer-presets/${id}`
    ] as const;
    }

    
export const getGetMixerPresetQueryOptions = <TData = Awaited<ReturnType<typeof getMixerPreset>>, TError = unknown>(songId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMixerPreset>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMixerPresetQueryKey(songId,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMixerPreset>>> = ({ signal }) => getMixerPreset(songId,id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(songId && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMixerPreset>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMixerPresetQueryResult = NonNullable<Awaited<ReturnType<typeof getMixerPreset>>>
export type GetMixerPresetQueryError = unknown


export function useGetMixerPreset<TData = Awaited<ReturnType<typeof getMixerPreset>>, TError = unknown>(
 songId: string,
    id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMixerPreset>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMixerPreset>>,
          TError,
          Awaited<ReturnType<typeof getMixerPreset>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMixerPreset<TData = Awaited<ReturnType<typeof getMixerPreset>>, TError = unknown>(
 songId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMixerPreset>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMixerPreset>>,
          TError,
          Awaited<ReturnType<typeof getMixerPreset>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMixerPreset<TData = Awaited<ReturnType<typeof getMixerPreset>>, TError = unknown>(
 songId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMixerPreset>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMixerPreset<TData = Awaited<ReturnType<typeof getMixerPreset>>, TError = unknown>(
 songId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMixerPreset>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMixerPresetQueryOptions(songId,id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateMixerPreset = (
    songId: string,
    id: string,
    updateMixerPresetRequest: UpdateMixerPresetRequest,
 ) => {
      
      
      return customInstance<ApiResponseOfMixerPreset>(
      {url: `/playback-api/songs/${songId}/mixer-presets/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateMixerPresetRequest
    },
      );
    }
  


export const getUpdateMixerPresetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMixerPreset>>, TError,{songId: string;id: string;data: UpdateMixerPresetRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMixerPreset>>, TError,{songId: string;id: string;data: UpdateMixerPresetRequest}, TContext> => {

const mutationKey = ['updateMixerPreset'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMixerPreset>>, {songId: string;id: string;data: UpdateMixerPresetRequest}> = (props) => {
          const {songId,id,data} = props ?? {};

          return  updateMixerPreset(songId,id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMixerPresetMutationResult = NonNullable<Awaited<ReturnType<typeof updateMixerPreset>>>
    export type UpdateMixerPresetMutationBody = UpdateMixerPresetRequest
    export type UpdateMixerPresetMutationError = unknown

    export const useUpdateMixerPreset = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMixerPreset>>, TError,{songId: string;id: string;data: UpdateMixerPresetRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMixerPreset>>,
        TError,
        {songId: string;id: string;data: UpdateMixerPresetRequest},
        TContext
      > => {

      const mutationOptions = getUpdateMixerPresetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteMixerPreset = (
    songId: string,
    id: string,
 ) => {
      
      
      return customInstance<ApiResponseOfObject>(
      {url: `/playback-api/songs/${songId}/mixer-presets/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteMixerPresetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMixerPreset>>, TError,{songId: string;id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteMixerPreset>>, TError,{songId: string;id: string}, TContext> => {

const mutationKey = ['deleteMixerPreset'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMixerPreset>>, {songId: string;id: string}> = (props) => {
          const {songId,id} = props ?? {};

          return  deleteMixerPreset(songId,id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMixerPresetMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMixerPreset>>>
    
    export type DeleteMixerPresetMutationError = unknown

    export const useDeleteMixerPreset = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMixerPreset>>, TError,{songId: string;id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMixerPreset>>,
        TError,
        {songId: string;id: string},
        TContext
      > => {

      const mutationOptions = getDeleteMixerPresetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    