/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * PlaybackService | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfListOfTrack,
  ApiResponseOfstring,
  UploadTrackBody
} from './models';

import { customInstance } from '../../axios-instance';





export const uploadTrack = (
    songId: string,
    uploadTrackBody: UploadTrackBody,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
uploadTrackBody.files.forEach(value => formData.append(`files`, value));

      return customInstance<ApiResponseOfListOfTrack>(
      {url: `/playback-api/songs/${songId}/tracks`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getUploadTrackMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadTrack>>, TError,{songId: string;data: UploadTrackBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadTrack>>, TError,{songId: string;data: UploadTrackBody}, TContext> => {

const mutationKey = ['uploadTrack'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadTrack>>, {songId: string;data: UploadTrackBody}> = (props) => {
          const {songId,data} = props ?? {};

          return  uploadTrack(songId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadTrackMutationResult = NonNullable<Awaited<ReturnType<typeof uploadTrack>>>
    export type UploadTrackMutationBody = UploadTrackBody
    export type UploadTrackMutationError = unknown

    export const useUploadTrack = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadTrack>>, TError,{songId: string;data: UploadTrackBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadTrack>>,
        TError,
        {songId: string;data: UploadTrackBody},
        TContext
      > => {

      const mutationOptions = getUploadTrackMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getTracks = (
    songId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfListOfTrack>(
      {url: `/playback-api/songs/${songId}/tracks`, method: 'GET', signal
    },
      );
    }
  



export const getGetTracksQueryKey = (songId?: string,) => {
    return [
    `/playback-api/songs/${songId}/tracks`
    ] as const;
    }

    
export const getGetTracksQueryOptions = <TData = Awaited<ReturnType<typeof getTracks>>, TError = unknown>(songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTracks>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTracksQueryKey(songId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTracks>>> = ({ signal }) => getTracks(songId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(songId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTracks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTracksQueryResult = NonNullable<Awaited<ReturnType<typeof getTracks>>>
export type GetTracksQueryError = unknown


export function useGetTracks<TData = Awaited<ReturnType<typeof getTracks>>, TError = unknown>(
 songId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTracks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTracks>>,
          TError,
          Awaited<ReturnType<typeof getTracks>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTracks<TData = Awaited<ReturnType<typeof getTracks>>, TError = unknown>(
 songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTracks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTracks>>,
          TError,
          Awaited<ReturnType<typeof getTracks>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTracks<TData = Awaited<ReturnType<typeof getTracks>>, TError = unknown>(
 songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTracks>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTracks<TData = Awaited<ReturnType<typeof getTracks>>, TError = unknown>(
 songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTracks>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTracksQueryOptions(songId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const downloadTrack = (
    songId: string,
    trackId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfstring>(
      {url: `/playback-api/songs/${songId}/tracks/${trackId}/download`, method: 'GET', signal
    },
      );
    }
  



export const getDownloadTrackQueryKey = (songId?: string,
    trackId?: string,) => {
    return [
    `/playback-api/songs/${songId}/tracks/${trackId}/download`
    ] as const;
    }

    
export const getDownloadTrackQueryOptions = <TData = Awaited<ReturnType<typeof downloadTrack>>, TError = unknown>(songId: string,
    trackId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTrack>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadTrackQueryKey(songId,trackId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadTrack>>> = ({ signal }) => downloadTrack(songId,trackId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(songId && trackId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadTrack>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadTrackQueryResult = NonNullable<Awaited<ReturnType<typeof downloadTrack>>>
export type DownloadTrackQueryError = unknown


export function useDownloadTrack<TData = Awaited<ReturnType<typeof downloadTrack>>, TError = unknown>(
 songId: string,
    trackId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTrack>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadTrack>>,
          TError,
          Awaited<ReturnType<typeof downloadTrack>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadTrack<TData = Awaited<ReturnType<typeof downloadTrack>>, TError = unknown>(
 songId: string,
    trackId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTrack>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadTrack>>,
          TError,
          Awaited<ReturnType<typeof downloadTrack>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadTrack<TData = Awaited<ReturnType<typeof downloadTrack>>, TError = unknown>(
 songId: string,
    trackId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTrack>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDownloadTrack<TData = Awaited<ReturnType<typeof downloadTrack>>, TError = unknown>(
 songId: string,
    trackId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadTrack>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadTrackQueryOptions(songId,trackId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




