/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * BandService | v1
 * OpenAPI spec version: 1.0.0
 */

export type ApiCodes = typeof ApiCodes[keyof typeof ApiCodes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiCodes = {
  Success: 'Success',
  ValidationFailed: 'ValidationFailed',
  Forbidden: 'Forbidden',
  NotFound: 'NotFound',
  Conflict: 'Conflict',
} as const;
