/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * BandService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Member } from './member';

export type ApiResponseOfListOfMemberValue = null | Member[];
