/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * BandService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApiCodes } from './apiCodes';
import type { ApiResponseOfintValue } from './apiResponseOfintValue';

export interface ApiResponseOfint {
  code: ApiCodes;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  value: ApiResponseOfintValue;
}
