/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * BandService | v1
 * OpenAPI spec version: 1.0.0
 */

export type InvitationStatus = typeof InvitationStatus[keyof typeof InvitationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvitationStatus = {
  Pending: 'Pending',
  Accepted: 'Accepted',
  Declined: 'Declined',
} as const;
