/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WBand.WebProxy | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SessionResponse {
  id: string;
  /** @nullable */
  username: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  name: string | null;
  /** @nullable */
  avatar: string | null;
  roles: string[];
  csrfToken: string;
}
