<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WolverineFx.Http" Version="6.24.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\Shared\Shared.csproj" />
    <ProjectReference Include="..\WBand.Modules.BandModule\WBand.Modules.BandModule.csproj" />
    <ProjectReference Include="..\WBand.Modules.FileModule\WBand.Modules.FileModule.csproj" />
    <ProjectReference Include="..\WBand.Modules.SongModule\WBand.Modules.SongModule.csproj" />
    <ProjectReference Include="..\WBand.Modules.StemModule\WBand.Modules.StemModule.csproj" />
  </ItemGroup>
</Project>
