/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * PlaybackService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApiCodes } from './apiCodes';
import type { ApiResponseOfListOfMixerPresetValue } from './apiResponseOfListOfMixerPresetValue';

export interface ApiResponseOfListOfMixerPreset {
  code: ApiCodes;
  value: ApiResponseOfListOfMixerPresetValue;
}
