/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * PlaybackService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TrackPreset } from './trackPreset';

export type CreateMixerPresetRequestOutput = null | TrackPreset;
