/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * PlaybackService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateMixerPresetRequestOutput } from './createMixerPresetRequestOutput';
import type { CreateMixerPresetRequestTracks } from './createMixerPresetRequestTracks';

export interface CreateMixerPresetRequest {
  name: string;
  output?: CreateMixerPresetRequestOutput;
  tracks?: CreateMixerPresetRequestTracks;
}
