/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * PlaybackService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TrackDurationSeconds } from './trackDurationSeconds';
import type { TrackUpdatedAt } from './trackUpdatedAt';
import type { TrackUpdatedBy } from './trackUpdatedBy';

export interface Track {
  id: string;
  songId: string;
  instrument: string;
  fileKey: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  durationSeconds?: TrackDurationSeconds;
  createdAt: string;
  createdBy: string;
  updatedAt?: TrackUpdatedAt;
  updatedBy?: TrackUpdatedBy;
}
