/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * PlaybackService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TrackPresetVolume } from './trackPresetVolume';
import type { TrackPresetPan } from './trackPresetPan';

export interface TrackPreset {
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  volume?: TrackPresetVolume;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  pan?: TrackPresetPan;
  muted?: boolean;
  solo?: boolean;
}
