/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * PlaybackService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateMixerPresetRequestName } from './updateMixerPresetRequestName';
import type { UpdateMixerPresetRequestOutput } from './updateMixerPresetRequestOutput';
import type { UpdateMixerPresetRequestTracks } from './updateMixerPresetRequestTracks';

export interface UpdateMixerPresetRequest {
  name?: UpdateMixerPresetRequestName;
  output?: UpdateMixerPresetRequestOutput;
  tracks?: UpdateMixerPresetRequestTracks;
}
