/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * BandService | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponse,
  ApiResponseOfBand,
  ApiResponseOfListOfBand,
  CreateBandRequest,
  UpdateBandRequest
} from './models';

import { customInstance } from '../../axios-instance';





export const createBand = (
    createBandRequest: CreateBandRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfBand>(
      {url: `/band-api/bands/bands`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBandRequest, signal
    },
      );
    }
  


export const getCreateBandMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBand>>, TError,{data: CreateBandRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createBand>>, TError,{data: CreateBandRequest}, TContext> => {

const mutationKey = ['createBand'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBand>>, {data: CreateBandRequest}> = (props) => {
          const {data} = props ?? {};

          return  createBand(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBandMutationResult = NonNullable<Awaited<ReturnType<typeof createBand>>>
    export type CreateBandMutationBody = CreateBandRequest
    export type CreateBandMutationError = unknown

    export const useCreateBand = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBand>>, TError,{data: CreateBandRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBand>>,
        TError,
        {data: CreateBandRequest},
        TContext
      > => {

      const mutationOptions = getCreateBandMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getListOfBands = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfListOfBand>(
      {url: `/band-api/bands/bands`, method: 'GET', signal
    },
      );
    }
  



export const getGetListOfBandsQueryKey = () => {
    return [
    `/band-api/bands/bands`
    ] as const;
    }

    
export const getGetListOfBandsQueryOptions = <TData = Awaited<ReturnType<typeof getListOfBands>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListOfBands>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListOfBandsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListOfBands>>> = ({ signal }) => getListOfBands(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListOfBands>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListOfBandsQueryResult = NonNullable<Awaited<ReturnType<typeof getListOfBands>>>
export type GetListOfBandsQueryError = unknown


export function useGetListOfBands<TData = Awaited<ReturnType<typeof getListOfBands>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListOfBands>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListOfBands>>,
          TError,
          Awaited<ReturnType<typeof getListOfBands>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListOfBands<TData = Awaited<ReturnType<typeof getListOfBands>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListOfBands>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListOfBands>>,
          TError,
          Awaited<ReturnType<typeof getListOfBands>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListOfBands<TData = Awaited<ReturnType<typeof getListOfBands>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListOfBands>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetListOfBands<TData = Awaited<ReturnType<typeof getListOfBands>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListOfBands>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListOfBandsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateBand = (
    bandId: string,
    updateBandRequest: UpdateBandRequest,
 ) => {
      
      
      return customInstance<ApiResponse>(
      {url: `/band-api/bands/bands/${bandId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateBandRequest
    },
      );
    }
  


export const getUpdateBandMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBand>>, TError,{bandId: string;data: UpdateBandRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateBand>>, TError,{bandId: string;data: UpdateBandRequest}, TContext> => {

const mutationKey = ['updateBand'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBand>>, {bandId: string;data: UpdateBandRequest}> = (props) => {
          const {bandId,data} = props ?? {};

          return  updateBand(bandId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateBandMutationResult = NonNullable<Awaited<ReturnType<typeof updateBand>>>
    export type UpdateBandMutationBody = UpdateBandRequest
    export type UpdateBandMutationError = unknown

    export const useUpdateBand = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBand>>, TError,{bandId: string;data: UpdateBandRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBand>>,
        TError,
        {bandId: string;data: UpdateBandRequest},
        TContext
      > => {

      const mutationOptions = getUpdateBandMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteBand = (
    bandId: string,
 ) => {
      
      
      return customInstance<ApiResponse>(
      {url: `/band-api/bands/bands/${bandId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteBandMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBand>>, TError,{bandId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteBand>>, TError,{bandId: string}, TContext> => {

const mutationKey = ['deleteBand'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBand>>, {bandId: string}> = (props) => {
          const {bandId} = props ?? {};

          return  deleteBand(bandId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBandMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBand>>>
    
    export type DeleteBandMutationError = unknown

    export const useDeleteBand = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBand>>, TError,{bandId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBand>>,
        TError,
        {bandId: string},
        TContext
      > => {

      const mutationOptions = getDeleteBandMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getBand = (
    bandId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfBand>(
      {url: `/band-api/bands/bands/${bandId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetBandQueryKey = (bandId?: string,) => {
    return [
    `/band-api/bands/bands/${bandId}`
    ] as const;
    }

    
export const getGetBandQueryOptions = <TData = Awaited<ReturnType<typeof getBand>>, TError = unknown>(bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBand>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBandQueryKey(bandId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBand>>> = ({ signal }) => getBand(bandId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(bandId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBand>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBandQueryResult = NonNullable<Awaited<ReturnType<typeof getBand>>>
export type GetBandQueryError = unknown


export function useGetBand<TData = Awaited<ReturnType<typeof getBand>>, TError = unknown>(
 bandId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBand>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBand>>,
          TError,
          Awaited<ReturnType<typeof getBand>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBand<TData = Awaited<ReturnType<typeof getBand>>, TError = unknown>(
 bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBand>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBand>>,
          TError,
          Awaited<ReturnType<typeof getBand>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBand<TData = Awaited<ReturnType<typeof getBand>>, TError = unknown>(
 bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBand>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetBand<TData = Awaited<ReturnType<typeof getBand>>, TError = unknown>(
 bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBand>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBandQueryOptions(bandId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




