/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * BandService | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfInvitation,
  ApiResponseOfListOfInvitation,
  ApiResponseOfboolean,
  CreateInvitationRequest
} from './models';

import { customInstance } from '../../axios-instance';





export const getBandInvitationList = (
    bandId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfListOfInvitation>(
      {url: `/band-api/bands/${bandId}/invitations`, method: 'GET', signal
    },
      );
    }
  



export const getGetBandInvitationListQueryKey = (bandId?: string,) => {
    return [
    `/band-api/bands/${bandId}/invitations`
    ] as const;
    }

    
export const getGetBandInvitationListQueryOptions = <TData = Awaited<ReturnType<typeof getBandInvitationList>>, TError = unknown>(bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBandInvitationList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBandInvitationListQueryKey(bandId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBandInvitationList>>> = ({ signal }) => getBandInvitationList(bandId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(bandId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBandInvitationList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBandInvitationListQueryResult = NonNullable<Awaited<ReturnType<typeof getBandInvitationList>>>
export type GetBandInvitationListQueryError = unknown


export function useGetBandInvitationList<TData = Awaited<ReturnType<typeof getBandInvitationList>>, TError = unknown>(
 bandId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBandInvitationList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBandInvitationList>>,
          TError,
          Awaited<ReturnType<typeof getBandInvitationList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBandInvitationList<TData = Awaited<ReturnType<typeof getBandInvitationList>>, TError = unknown>(
 bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBandInvitationList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBandInvitationList>>,
          TError,
          Awaited<ReturnType<typeof getBandInvitationList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBandInvitationList<TData = Awaited<ReturnType<typeof getBandInvitationList>>, TError = unknown>(
 bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBandInvitationList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetBandInvitationList<TData = Awaited<ReturnType<typeof getBandInvitationList>>, TError = unknown>(
 bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBandInvitationList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBandInvitationListQueryOptions(bandId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createBandInvitation = (
    bandId: string,
    createInvitationRequest: CreateInvitationRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfInvitation>(
      {url: `/band-api/bands/${bandId}/invitations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createInvitationRequest, signal
    },
      );
    }
  


export const getCreateBandInvitationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBandInvitation>>, TError,{bandId: string;data: CreateInvitationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createBandInvitation>>, TError,{bandId: string;data: CreateInvitationRequest}, TContext> => {

const mutationKey = ['createBandInvitation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBandInvitation>>, {bandId: string;data: CreateInvitationRequest}> = (props) => {
          const {bandId,data} = props ?? {};

          return  createBandInvitation(bandId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBandInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof createBandInvitation>>>
    export type CreateBandInvitationMutationBody = CreateInvitationRequest
    export type CreateBandInvitationMutationError = unknown

    export const useCreateBandInvitation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBandInvitation>>, TError,{bandId: string;data: CreateInvitationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBandInvitation>>,
        TError,
        {bandId: string;data: CreateInvitationRequest},
        TContext
      > => {

      const mutationOptions = getCreateBandInvitationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteBandInvitation = (
    bandId: string,
    invitationId: string,
 ) => {
      
      
      return customInstance<ApiResponseOfboolean>(
      {url: `/band-api/bands/${bandId}/invitations/${invitationId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteBandInvitationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBandInvitation>>, TError,{bandId: string;invitationId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteBandInvitation>>, TError,{bandId: string;invitationId: string}, TContext> => {

const mutationKey = ['deleteBandInvitation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBandInvitation>>, {bandId: string;invitationId: string}> = (props) => {
          const {bandId,invitationId} = props ?? {};

          return  deleteBandInvitation(bandId,invitationId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBandInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBandInvitation>>>
    
    export type DeleteBandInvitationMutationError = unknown

    export const useDeleteBandInvitation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBandInvitation>>, TError,{bandId: string;invitationId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBandInvitation>>,
        TError,
        {bandId: string;invitationId: string},
        TContext
      > => {

      const mutationOptions = getDeleteBandInvitationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    