/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * BandService | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfListOfMember,
  ApiResponseOfMember,
  ApiResponseOfboolean,
  UpdateMemberRoleRequest
} from './models';

import { customInstance } from '../../axios-instance';





export const getMembers = (
    bandId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfListOfMember>(
      {url: `/band-api/bands/${bandId}/members`, method: 'GET', signal
    },
      );
    }
  



export const getGetMembersQueryKey = (bandId?: string,) => {
    return [
    `/band-api/bands/${bandId}/members`
    ] as const;
    }

    
export const getGetMembersQueryOptions = <TData = Awaited<ReturnType<typeof getMembers>>, TError = unknown>(bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMembersQueryKey(bandId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMembers>>> = ({ signal }) => getMembers(bandId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(bandId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMembersQueryResult = NonNullable<Awaited<ReturnType<typeof getMembers>>>
export type GetMembersQueryError = unknown


export function useGetMembers<TData = Awaited<ReturnType<typeof getMembers>>, TError = unknown>(
 bandId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMembers>>,
          TError,
          Awaited<ReturnType<typeof getMembers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMembers<TData = Awaited<ReturnType<typeof getMembers>>, TError = unknown>(
 bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMembers>>,
          TError,
          Awaited<ReturnType<typeof getMembers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMembers<TData = Awaited<ReturnType<typeof getMembers>>, TError = unknown>(
 bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMembers<TData = Awaited<ReturnType<typeof getMembers>>, TError = unknown>(
 bandId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMembersQueryOptions(bandId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateMemberRole = (
    bandId: string,
    memberId: string,
    updateMemberRoleRequest: UpdateMemberRoleRequest,
 ) => {
      
      
      return customInstance<ApiResponseOfMember>(
      {url: `/band-api/bands/${bandId}/members/${memberId}/role`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateMemberRoleRequest
    },
      );
    }
  


export const getUpdateMemberRoleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMemberRole>>, TError,{bandId: string;memberId: string;data: UpdateMemberRoleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMemberRole>>, TError,{bandId: string;memberId: string;data: UpdateMemberRoleRequest}, TContext> => {

const mutationKey = ['updateMemberRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMemberRole>>, {bandId: string;memberId: string;data: UpdateMemberRoleRequest}> = (props) => {
          const {bandId,memberId,data} = props ?? {};

          return  updateMemberRole(bandId,memberId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMemberRoleMutationResult = NonNullable<Awaited<ReturnType<typeof updateMemberRole>>>
    export type UpdateMemberRoleMutationBody = UpdateMemberRoleRequest
    export type UpdateMemberRoleMutationError = unknown

    export const useUpdateMemberRole = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMemberRole>>, TError,{bandId: string;memberId: string;data: UpdateMemberRoleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMemberRole>>,
        TError,
        {bandId: string;memberId: string;data: UpdateMemberRoleRequest},
        TContext
      > => {

      const mutationOptions = getUpdateMemberRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const removeMember = (
    bandId: string,
    memberId: string,
 ) => {
      
      
      return customInstance<ApiResponseOfboolean>(
      {url: `/band-api/bands/${bandId}/members/${memberId}`, method: 'DELETE'
    },
      );
    }
  


export const getRemoveMemberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeMember>>, TError,{bandId: string;memberId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removeMember>>, TError,{bandId: string;memberId: string}, TContext> => {

const mutationKey = ['removeMember'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeMember>>, {bandId: string;memberId: string}> = (props) => {
          const {bandId,memberId} = props ?? {};

          return  removeMember(bandId,memberId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveMemberMutationResult = NonNullable<Awaited<ReturnType<typeof removeMember>>>
    
    export type RemoveMemberMutationError = unknown

    export const useRemoveMember = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeMember>>, TError,{bandId: string;memberId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeMember>>,
        TError,
        {bandId: string;memberId: string},
        TContext
      > => {

      const mutationOptions = getRemoveMemberMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    