import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
    ru: { translation: {
        language: { label: "Язык", ru: "Русский", en: "English" },
        common: { loading: "Загрузка...", cancel: "Отмена", save: "Сохранить", edit: "Редактировать", delete: "Удалить", view: "Просмотреть", restore: "Восстановить", current: "Текущая", band: "Группа", allBands: "Все группы", selectBand: "Выберите группу", noData: "Нет данных", name: "Название", actions: "Действия", add: "Добавить", update: "Обновить", updating: "Обновление...", adding: "Добавление...", success: "Готово", error: "Ошибка", noResults: "Ничего не найдено", author: "Автор", added: "Добавлена" },
        nav: { dashboard: "Главная", invitations: "Мои приглашения", songs: "Песни", playlists: "Плейлисты", playback: "Воспроизведение", stage: "Сцена", chat: "Чат", search: "Поиск", bands: "Группы" },
        errors: {
            generic: "Что-то пошло не так.", forbidden: "Недостаточно прав.",
            invitation_already_pending: "Для этого пользователя уже есть активное приглашение.",
            invitation_already_created: "Этого пользователя уже приглашали в группу. Повторное приглашение невозможно.",
            member_already_exists: "Пользователь уже является участником этой группы.",
            owner_cannot_leave: "Собственник должен сначала передать владение другому участнику.",
            already_member: "Вы уже состоите в этой группе."
        },
        band: {
            formerTitle: "Ранее покинутые группы", formerHint: "Вы можете вернуться самостоятельно с ролью Участник.", leftAt: "Покинута {{date}}", rejoin: "Вернуться", rejoined: "Вы снова вступили в группу с ролью Участник", rejoinFailed: "Не удалось вернуться в группу",
            leave: "Покинуть группу", leaveConfirm: "Покинуть группу? Доступ к её песням будет потерян.", left: "Вы покинули группу", leaveFailed: "Не удалось покинуть группу",
            roles: { Owner: "Собственник", Admin: "Администратор", Member: "Участник" }, roleAdminSet: "Назначена роль Администратор", roleMemberSet: "Назначена роль Участник", roleChangeFailed: "Не удалось изменить роль",
            invitationSent: "Приглашение отправлено", invitationPendingTitle: "Приглашение уже отправлено", invitationFailed: "Не удалось отправить приглашение", listTitle: "Группы", addBand: "Добавить группу", addHint: "Группа объединяет музыкантов, которые выступают вместе.", editBand: "Редактировать группу", bandName: "Название группы", created: "Группа создана", updated: "Группа обновлена", exists: "Группа с таким названием уже существует", createForbidden: "Недостаточно прав для создания группы", updateForbidden: "Недостаточно прав для изменения группы", notFound: "Группа не найдена", notFoundHint: "Группа не существует или у вас нет доступа к ней.", information: "Информация о группе", creationDetails: "Сведения о создании", createdAt: "Создана", createdBy: "Создал", members: "Участники", invitations: "Приглашения", bandMembers: "Участники группы",
            invite: "Пригласить участника", inviteTitle: "Пригласить нового участника", inviteHint: "Отправьте приглашение присоединиться к группе. Пользователь должен принять его.", email: "Email", role: "Роль", send: "Отправить приглашение", sending: "Отправка...", joined: "Вступил {{date}}", makeAdmin: "Назначить администратором", makeMember: "Назначить участником", removeMember: "Удалить участника", loadMembersFailed: "Не удалось загрузить участников или нет доступа.", noMembers: "Участников нет"
        },
        songs: {
            title: "Песни", add: "Добавить песню", groupColumn: "Группа", insufficient: "Недостаточно прав", memberReadOnly: "Участник с ролью Member может только просматривать песни.", noBand: "Нет группы", createBandFirst: "Сначала создайте группу",
            history: "История версий", currentVersion: "Текущая версия: {{version}}", version: "Версия {{version}}", changedBy: "Изменил: {{actor}}", restored: "Версия восстановлена", restoreFailed: "Не удалось восстановить версию", previewTitle: "Версия {{version}}", previewHint: "Предпросмотр сохранённой версии без возможности редактирования.", previewFailed: "Не удалось загрузить версию.", restoreThis: "Восстановить эту версию", restoring: "Восстановление...", thisIsCurrent: "Это текущая версия",
            fields: { title: "Название", authors: "Авторы", key: "Тональность", tempoChanges: "Изменения темпа", signature: "Размер", countIn: "Тактов отсчёта", sections: "Секции", lyrics: "Текст", chords: "Аккорды", fromBar: "с такта {{bar}}" }, sectionsPlaceholder: "Куплет:1-8\nПрипев:9-16", description: "Управляйте коллекцией песен", search: "Поиск песен...", empty: "Песен пока нет", emptyHint: "Начните наполнять репертуар", addFirst: "Добавить первую песню", loadFailed: "Не удалось загрузить песни", deleted: "Песня удалена", deleteFailed: "Не удалось удалить песню", deleteTitle: "Удалить песню", deleteConfirm: "Удалить песню «{{title}}»? Это действие нельзя отменить.", loadingSong: "Загрузка песни...", loadSongFailed: "Не удалось загрузить песню", details: "Сведения о песне", playbackMixer: "Playback и микшер", editSong: "Редактировать песню", createSong: "Новая песня"
        },
        songActions: { created: "Песня создана", updated: "Песня обновлена", createFailed: "Не удалось создать песню", updateFailed: "Не удалось обновить песню", validationError: "Ошибка проверки", titleRequired: "Укажите название песни", authorArtist: "Автор/исполнитель", notFound: "Песня не найдена", createdAt: "Создана {{date}}", updateHint: "Измените сведения о песне", createHint: "Добавьте новую песню в репертуар", lyricsPlaceholder: "Введите текст песни...", chordsPlaceholder: "Введите последовательность аккордов...", create: "Создать песню", update: "Обновить песню" },
        dashboard: { title: "Главная", welcome: "Добро пожаловать в панель управления WBand.", invitations: "Мои приглашения", quickActions: "Быстрые действия", quickActionsHint: "Создавайте песни и плейлисты или управляйте группами." },
        invitations: { title: "Мои приглашения", subtitle: "Управляйте приглашениями в группы.", bandInvitation: "Приглашение в группу", invitedBy: "Пригласил: {{email}}", band: "Группа: {{name}}", pending: "Ожидает", accepted: "Принято", declined: "Отклонено", revoked: "Отозвано", expired: "Истекло", accept: "Принять", decline: "Отклонить", pendingTitle: "Ожидающие приглашения", recentTitle: "Недавние приглашения", empty: "Приглашений нет", emptyBand: "Для этой группы приглашений нет", loadFailed: "Не удалось загрузить приглашения или нет доступа." },
        user: { user: "Пользователь", superAdmin: "Суперадминистратор", moderator: "Модератор", account: "Аккаунт", billing: "Оплата", notifications: "Уведомления", logout: "Выйти" },
        home: {
            badge: "Цифровой помощник музыкантов", title: "WBand: всё для подготовки и выступлений вашей группы", subtitle: "Управляйте репертуаром, планируйте мероприятия, храните плейбеки и тексты песен, координируйте работу группы в одном приложении.", start: "Начать работу", learn: "Подробнее о возможностях", featuresTitle: "Возможности приложения", featuresSubtitle: "Комплексное решение для организации работы музыкальной группы и подготовки к выступлениям", ctaTitle: "Готовы вывести вашу группу на новый уровень?", ctaText: "Присоединяйтесь к WBand и управляйте всеми аспектами работы группы в одном месте.", createBand: "Создать группу",
            stats: ["групп используют приложение", "песен в базе данных", "доступ к вашему репертуару"],
            features: [{ title: "База песен и плейбеков", text: "Храните весь репертуар в одном месте. Добавляйте треки, тексты песен, аккорды, плейбеки и нотные материалы." }, { title: "Планирование мероприятий", text: "Организуйте выступления, репетиции и концерты. Управляйте расписанием группы и отслеживайте важные даты." }, { title: "Общение и координация", text: "Обсуждайте сет-листы, договаривайтесь о деталях выступлений и делитесь идеями прямо в приложении." }, { title: "Управление составом", text: "Добавляйте участников группы, распределяйте роли и отслеживайте доступность музыкантов." }],
            steps: [{ title: "Создайте группу", text: "Зарегистрируйтесь, создайте свою группу и пригласите участников." }, { title: "Наполните базу", text: "Добавьте песни, плейбеки, тексты и ноты." }, { title: "Планируйте выступления", text: "Создавайте мероприятия и формируйте программу выступления." }]
        }
    }},
    en: { translation: {
        language: { label: "Language", ru: "Русский", en: "English" },
        common: { loading: "Loading...", cancel: "Cancel", save: "Save", edit: "Edit", delete: "Delete", view: "View", restore: "Restore", current: "Current", band: "Band", allBands: "All bands", selectBand: "Select a band", noData: "No data", name: "Name", actions: "Actions", add: "Add", update: "Update", updating: "Updating...", adding: "Adding...", success: "Success", error: "Error", noResults: "No results", author: "Author", added: "Added" },
        nav: { dashboard: "Dashboard", invitations: "My Invitations", songs: "Songs", playlists: "Playlists", playback: "Playback", stage: "Stage Mode", chat: "Chat", search: "Search", bands: "Bands" },
        errors: { generic: "Something went wrong.", forbidden: "You do not have permission.", invitation_already_pending: "An active invitation already exists for this user.", invitation_already_created: "This user has already been invited. Invitations can only be sent once.", member_already_exists: "This user is already a band member.", owner_cannot_leave: "Transfer ownership before leaving the band.", already_member: "You are already a member of this band." },
        band: { formerTitle: "Previously left bands", formerHint: "You can rejoin with the Member role.", leftAt: "Left on {{date}}", rejoin: "Rejoin", rejoined: "You rejoined the band as a Member", rejoinFailed: "Failed to rejoin the band", leave: "Leave band", leaveConfirm: "Leave this band? You will lose access to its songs.", left: "You left the band", leaveFailed: "Failed to leave the band", roles: { Owner: "Owner", Admin: "Administrator", Member: "Member" }, roleAdminSet: "Administrator role assigned", roleMemberSet: "Member role assigned", roleChangeFailed: "Failed to change role", invitationSent: "Invitation sent", invitationPendingTitle: "Invitation already sent", invitationFailed: "Failed to send invitation", listTitle: "Bands", addBand: "Add band", addHint: "A band brings together musicians who perform together.", editBand: "Edit band", bandName: "Band name", created: "Band created", updated: "Band updated", exists: "A band with this name already exists", createForbidden: "You do not have permission to create a band", updateForbidden: "You do not have permission to update this band", notFound: "Band not found", notFoundHint: "The band does not exist or you do not have access to it.", information: "Band information", creationDetails: "Creation details", createdAt: "Created", createdBy: "Created by", members: "Members", invitations: "Invitations", bandMembers: "Band members", invite: "Invite member", inviteTitle: "Invite a new member", inviteHint: "Send an invitation to join this band. The user must accept it.", email: "Email", role: "Role", send: "Send invitation", sending: "Sending...", joined: "Joined {{date}}", makeAdmin: "Make administrator", makeMember: "Make member", removeMember: "Remove member", loadMembersFailed: "Failed to load members or you do not have access.", noMembers: "No members found" },
        songs: { title: "Songs", add: "Add song", groupColumn: "Band", insufficient: "Insufficient permissions", memberReadOnly: "Members can only view songs.", noBand: "No band", createBandFirst: "Create a band first", history: "Version history", currentVersion: "Current version: {{version}}", version: "Version {{version}}", changedBy: "Changed by: {{actor}}", restored: "Version restored", restoreFailed: "Failed to restore version", previewTitle: "Version {{version}}", previewHint: "Read-only preview of the saved version.", previewFailed: "Failed to load version.", restoreThis: "Restore this version", restoring: "Restoring...", thisIsCurrent: "This is the current version", fields: { title: "Title", authors: "Authors", key: "Key", tempoChanges: "Tempo changes", signature: "Time signature", countIn: "Count-in bars", sections: "Sections", lyrics: "Lyrics", chords: "Chords", fromBar: "from bar {{bar}}" }, sectionsPlaceholder: "Verse:1-8\nChorus:9-16", description: "Manage your song collection", search: "Search songs...", empty: "No songs yet", emptyHint: "Start building your repertoire", addFirst: "Add your first song", loadFailed: "Failed to load songs", deleted: "Song deleted", deleteFailed: "Failed to delete song", deleteTitle: "Delete song", deleteConfirm: "Delete “{{title}}”? This action cannot be undone.", loadingSong: "Loading song...", loadSongFailed: "Failed to load song", details: "Song details", playbackMixer: "Playback & mixer", editSong: "Edit song", createSong: "New song" },
        songActions: { created: "Song created", updated: "Song updated", createFailed: "Failed to create song", updateFailed: "Failed to update song", validationError: "Validation error", titleRequired: "Enter a song title", authorArtist: "Author/artist", notFound: "Song not found", createdAt: "Created {{date}}", updateHint: "Update the song details", createHint: "Add a new song to your repertoire", lyricsPlaceholder: "Enter song lyrics...", chordsPlaceholder: "Enter chord progression...", create: "Create song", update: "Update song" },
        dashboard: { title: "Home", welcome: "Welcome to your WBand dashboard.", invitations: "My invitations", quickActions: "Quick actions", quickActionsHint: "Create songs and playlists or manage your bands." },
        invitations: { title: "My invitations", subtitle: "Manage your band invitations.", bandInvitation: "Band invitation", invitedBy: "Invited by: {{email}}", band: "Band: {{name}}", pending: "Pending", accepted: "Accepted", declined: "Declined", revoked: "Revoked", expired: "Expired", accept: "Accept", decline: "Decline", pendingTitle: "Pending invitations", recentTitle: "Recent invitations", empty: "No invitations found", emptyBand: "No invitations found for this band", loadFailed: "Failed to load invitations or you do not have access." },
        user: { user: "User", superAdmin: "Super administrator", moderator: "Moderator", account: "Account", billing: "Billing", notifications: "Notifications", logout: "Log out" },
        home: { badge: "Digital assistant for musicians", title: "WBand: everything your band needs to prepare and perform", subtitle: "Manage repertoire, plan events, store playbacks and lyrics, and coordinate your band in one place.", start: "Get started", learn: "Explore features", featuresTitle: "Application features", featuresSubtitle: "A complete solution for band organization and performance preparation", ctaTitle: "Ready to take your band to the next level?", ctaText: "Join WBand and manage every aspect of your band in one place.", createBand: "Create a band", stats: ["bands use the application", "songs in the database", "access to your repertoire"], features: [{ title: "Songs and playbacks", text: "Keep your repertoire in one place, including tracks, lyrics, chords, playbacks, and sheet music." }, { title: "Event planning", text: "Organize performances, rehearsals, concerts, schedules, and important dates." }, { title: "Communication", text: "Discuss set lists, performance details, and ideas directly in the app." }, { title: "Member management", text: "Invite band members, assign roles, and track availability." }], steps: [{ title: "Create a band", text: "Register, create your band, and invite members." }, { title: "Build your library", text: "Add songs, playbacks, lyrics, and sheet music." }, { title: "Plan performances", text: "Create events and build performance programs." }] }
    }}
} as const;

void i18n.use(initReactI18next).init({
    resources,
    lng: localStorage.getItem("wband-language") ?? "ru",
    fallbackLng: "ru",
    supportedLngs: ["ru", "en"],
    interpolation: { escapeValue: false },
});

export default i18n;
