/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * SongService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TableResponseOfSong } from './tableResponseOfSong';

export type ApiResponseOfTableResponseOfSongValue = null | TableResponseOfSong;
