/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * SongService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Song } from './song';

export type ApiResponseOfSongValue = null | Song;
