/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * SongService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApiCodes } from './apiCodes';
import type { ApiResponseOfSongValue } from './apiResponseOfSongValue';

export interface ApiResponseOfSong {
  code: ApiCodes;
  value: ApiResponseOfSongValue;
}
