/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * SongService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSongRequestAuthor } from './createSongRequestAuthor';
import type { CreateSongRequestLyrics } from './createSongRequestLyrics';
import type { CreateSongRequestChords } from './createSongRequestChords';
import type { CreateSongRequestKey } from './createSongRequestKey';
import type { CreateSongRequestBpm } from './createSongRequestBpm';

export interface CreateSongRequest {
  bandId: string;
  title: string;
  author: CreateSongRequestAuthor;
  lyrics: CreateSongRequestLyrics;
  chords: CreateSongRequestChords;
  key: CreateSongRequestKey;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  bpm: CreateSongRequestBpm;
}
