/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * BandService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Invitation } from './invitation';

export type ApiResponseOfListOfInvitationValue = null | Invitation[];
