/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * BandService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MemberRole } from './memberRole';
import type { InvitationStatus } from './invitationStatus';

export interface Invitation {
  id: string;
  inviterId: string;
  inviterEmail: string;
  inviteeEmail: string;
  bandId: string;
  role: MemberRole;
  status: InvitationStatus;
}
