/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * BandService | v1
 * OpenAPI spec version: 1.0.0
 */

export type MemberRole = typeof MemberRole[keyof typeof MemberRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberRole = {
  Owner: 'Owner',
  Admin: 'Admin',
  Member: 'Member',
} as const;
