/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * SongService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApiCodes } from './apiCodes';
import type { ApiResponseOfTableResponseOfSongValue } from './apiResponseOfTableResponseOfSongValue';

export interface ApiResponseOfTableResponseOfSong {
  code: ApiCodes;
  value: ApiResponseOfTableResponseOfSongValue;
}
