/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * SongService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSongRequestAuthor } from './createSongRequestAuthor';
import type { CreateSongRequestKey } from './createSongRequestKey';
import type { CreateSongRequestBpm } from './createSongRequestBpm';

export interface CreateSongRequest {
  bandId: string;
  title: string;
  author: CreateSongRequestAuthor;
  key: CreateSongRequestKey;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  bpm: CreateSongRequestBpm;
  authors?: string[];
  tempoTrack?: { bar: number; bpm: number }[];
  timeSignatureTrack?: { bar: number; beats: number; beatUnit: number }[];
  countInBars?: number;
}
