<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Auth\Auth.csproj" />
    <ProjectReference Include="..\..\Common\Shared\Shared.csproj" />
    <ProjectReference Include="..\..\WBand.Modules.FileModule\WBand.Modules.FileModule.csproj" />
    <ProjectReference Include="..\..\WBand.Modules.UserModule\WBand.Modules.UserModule.csproj" />
  </ItemGroup>

</Project>
