<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>wband-webapi-development</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Auth\Auth.csproj" />
    <ProjectReference Include="..\..\Common\Shared\Shared.csproj" />
    <ProjectReference Include="..\..\WBand.Modules.FileModule\WBand.Modules.FileModule.csproj" />
    <ProjectReference Include="..\..\WBand.Modules.BandModule\WBand.Modules.BandModule.csproj" />
    <ProjectReference Include="..\..\WBand.Modules.UserModule\WBand.Modules.UserModule.csproj" />
    <ProjectReference Include="..\..\WBand.Modules.SongModule\WBand.Modules.SongModule.csproj" />
    <ProjectReference Include="..\..\WBand.Modules.PlaylistModule\WBand.Modules.PlaylistModule.csproj" />
  </ItemGroup>

</Project>
