/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * SongService | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfSong,
  ApiResponseOfTableResponseOfSong,
  ApiResponseOfboolean,
  CreateSongRequest,
  GetListOfSongsParams,
  UpdateSongRequest
} from './models';

import { customInstance } from '../../axios-instance';





export const createSong = (
    createSongRequest: CreateSongRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfSong>(
      {url: `/song-api/songs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSongRequest, signal
    },
      );
    }
  


export const getCreateSongMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSong>>, TError,{data: CreateSongRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createSong>>, TError,{data: CreateSongRequest}, TContext> => {

const mutationKey = ['createSong'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSong>>, {data: CreateSongRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSong(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSongMutationResult = NonNullable<Awaited<ReturnType<typeof createSong>>>
    export type CreateSongMutationBody = CreateSongRequest
    export type CreateSongMutationError = unknown

    export const useCreateSong = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSong>>, TError,{data: CreateSongRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSong>>,
        TError,
        {data: CreateSongRequest},
        TContext
      > => {

      const mutationOptions = getCreateSongMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getListOfSongs = (
    params: GetListOfSongsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfTableResponseOfSong>(
      {url: `/song-api/songs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetListOfSongsQueryKey = (params?: GetListOfSongsParams,) => {
    return [
    `/song-api/songs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetListOfSongsQueryOptions = <TData = Awaited<ReturnType<typeof getListOfSongs>>, TError = unknown>(params: GetListOfSongsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListOfSongs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListOfSongsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListOfSongs>>> = ({ signal }) => getListOfSongs(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListOfSongs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListOfSongsQueryResult = NonNullable<Awaited<ReturnType<typeof getListOfSongs>>>
export type GetListOfSongsQueryError = unknown


export function useGetListOfSongs<TData = Awaited<ReturnType<typeof getListOfSongs>>, TError = unknown>(
 params: GetListOfSongsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListOfSongs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListOfSongs>>,
          TError,
          Awaited<ReturnType<typeof getListOfSongs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListOfSongs<TData = Awaited<ReturnType<typeof getListOfSongs>>, TError = unknown>(
 params: GetListOfSongsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListOfSongs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListOfSongs>>,
          TError,
          Awaited<ReturnType<typeof getListOfSongs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListOfSongs<TData = Awaited<ReturnType<typeof getListOfSongs>>, TError = unknown>(
 params: GetListOfSongsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListOfSongs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetListOfSongs<TData = Awaited<ReturnType<typeof getListOfSongs>>, TError = unknown>(
 params: GetListOfSongsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListOfSongs>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListOfSongsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getSong = (
    songId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseOfSong>(
      {url: `/song-api/songs/${songId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetSongQueryKey = (songId?: string,) => {
    return [
    `/song-api/songs/${songId}`
    ] as const;
    }

    
export const getGetSongQueryOptions = <TData = Awaited<ReturnType<typeof getSong>>, TError = unknown>(songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSong>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSongQueryKey(songId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSong>>> = ({ signal }) => getSong(songId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(songId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSong>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSongQueryResult = NonNullable<Awaited<ReturnType<typeof getSong>>>
export type GetSongQueryError = unknown


export function useGetSong<TData = Awaited<ReturnType<typeof getSong>>, TError = unknown>(
 songId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSong>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSong>>,
          TError,
          Awaited<ReturnType<typeof getSong>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSong<TData = Awaited<ReturnType<typeof getSong>>, TError = unknown>(
 songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSong>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSong>>,
          TError,
          Awaited<ReturnType<typeof getSong>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSong<TData = Awaited<ReturnType<typeof getSong>>, TError = unknown>(
 songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSong>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSong<TData = Awaited<ReturnType<typeof getSong>>, TError = unknown>(
 songId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSong>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSongQueryOptions(songId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateSong = (
    songId: string,
    updateSongRequest: UpdateSongRequest,
 ) => {
      
      
      return customInstance<ApiResponseOfSong>(
      {url: `/song-api/songs/${songId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateSongRequest
    },
      );
    }
  


export const getUpdateSongMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSong>>, TError,{songId: string;data: UpdateSongRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSong>>, TError,{songId: string;data: UpdateSongRequest}, TContext> => {

const mutationKey = ['updateSong'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSong>>, {songId: string;data: UpdateSongRequest}> = (props) => {
          const {songId,data} = props ?? {};

          return  updateSong(songId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSongMutationResult = NonNullable<Awaited<ReturnType<typeof updateSong>>>
    export type UpdateSongMutationBody = UpdateSongRequest
    export type UpdateSongMutationError = unknown

    export const useUpdateSong = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSong>>, TError,{songId: string;data: UpdateSongRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSong>>,
        TError,
        {songId: string;data: UpdateSongRequest},
        TContext
      > => {

      const mutationOptions = getUpdateSongMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteSong = (
    songId: string,
 ) => {
      
      
      return customInstance<ApiResponseOfboolean>(
      {url: `/song-api/songs/${songId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteSongMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSong>>, TError,{songId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteSong>>, TError,{songId: string}, TContext> => {

const mutationKey = ['deleteSong'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSong>>, {songId: string}> = (props) => {
          const {songId} = props ?? {};

          return  deleteSong(songId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteSongMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSong>>>
    
    export type DeleteSongMutationError = unknown

    export const useDeleteSong = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSong>>, TError,{songId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSong>>,
        TError,
        {songId: string},
        TContext
      > => {

      const mutationOptions = getDeleteSongMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    